package enums;

/**
 * Các Features từ đề bài
 */
public enum COMMAND {
    GET_BALANCE, CASH_IN, CREATE_BILL, UPDATE_BILL, DELETE_BILL, LIST_BILL, PAY, DUE_DATE, SCHEDULE, LIST_PAYMENT, SEARCH_BILL_BY_PROVIDER, EXIT;
}
